version: "3.5"

services:
    influxdb:
        image: influxdb:latest
        container_name: influxdb
        hostname: influxdb
        restart: unless-stopped
        volumes:
#            - type: bind
#              source: ./influxdb.conf
#              target: /etc/influxdb/influxdb.conf
#              read_only: true
            - type: bind
              source: ./influxdb
              target: /var/lib/influxdb
        ports:
            - "${INFLUXDB_PORTS:-8086:8086}"
#        env_file:
#            - influxdb.env

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        hostname: grafana
        restart: unless-stopped
#        user: "${PWD_USER:-1000:1000}"
        user: 0:0
        volumes:
            - type: bind
              source: ./grafana
              target: /var/lib/grafana
        ports:
            - "3000:3000"
#        env_file:
#            - grafana.env
        depends_on:
            - influxdb
