version: "3.5"

#volumes:
#    influxdb2_data: # see https://github.com/containers/podman-compose/issues/746

services:
    influxdb:
        image: influxdb:latest
        container_name: influxdb
        hostname: influxdb
        restart: unless-stopped
#        privileged: true
#        userns_mode: keep-id:uid=501
#        user: 501
#        volumes:
#            - /tmp/influxdb2:/var/lib/influxdb2
#           - ./influxdb2:/var/lib/influxdb2
#            - influxdb2_data:/var/lib/influxdb2
#            - type: bind
#              source: ./influxdb.conf
#             target: /etc/influxdb/influxdb.conf
#             read_only: true
        ports:
            - "${INFLUXDB_PORTS:-8086:8086}"
        env_file:
            - influxdb.env

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        hostname: grafana
        restart: unless-stopped
#        user: "${PWD_USER:-1000:1000}"
#        user: 0:0
#        user: 501
#        volumes:
#            - ./grafana:/var/lib/grafana
        ports:
            - "3000:3000"
#        env_file:
#            - grafana.env
        depends_on:
            - influxdb
